// Socket event name constants — single source of truth
export const SOCKET_EVENTS = {
  // Room
  ROOM_JOIN: 'ROOM:JOIN',
  ROOM_LEAVE: 'ROOM:LEAVE',
  ROOM_USER_JOINED: 'ROOM:USER_JOINED',
  ROOM_USER_LEFT: 'ROOM:USER_LEFT',
  ROOM_USERS_LIST: 'ROOM:USERS_LIST',

  // Canvas
  CANVAS_STROKE_START: 'CANVAS:STROKE_START',
  CANVAS_STROKE_MOVE: 'CANVAS:STROKE_MOVE',
  CANVAS_STROKE_END: 'CANVAS:STROKE_END',
  CANVAS_SHAPE: 'CANVAS:SHAPE',
  CANVAS_TEXT: 'CANVAS:TEXT',
  CANVAS_UNDO: 'CANVAS:UNDO',
  CANVAS_REDO: 'CANVAS:REDO',
  CANVAS_CLEAR: 'CANVAS:CLEAR',
  CANVAS_STATE_SYNC: 'CANVAS:STATE_SYNC',
  CANVAS_PAGE_ADDED: 'CANVAS:PAGE_ADDED',
  CANVAS_BULK_LOAD: 'CANVAS:BULK_LOAD',

  // Cursor
  CURSOR_MOVE: 'CURSOR:MOVE',
  CURSOR_POSITIONS: 'CURSOR:POSITIONS',

  // System
  ERROR: 'ERROR',
};
